package edu.desu.sortsearchutils;

import edu.desu.helperstaticmethods.HelperStaticMethods;
import edu.desu.sortutils.InsertionSort;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class InsertionSortTests {

    @Test
    @DisplayName("Test generateReverseSequentialIntArray generates reverse sorted array")
    void testGenerateReverseSequentialIntArray() {
        int size = 5;
        int[] result = HelperStaticMethods.generateReverseSequentialIntArray(size);
        int[] expected = {4, 3, 2, 1, 0};
        Assertions.assertArrayEquals(expected, result);
    }

    @Test
    @DisplayName("Test insertionSort on standard unsorted array")
    void testInsertionSortUnsortedArray() {
        int[] input = {5, 3, 1, 4, 2};
        int[] expected = {1, 2, 3, 4, 5};
        InsertionSort.insertionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test insertionSort on already sorted array")
    void testInsertionSortAlreadySortedArray() {
        int[] input = {1, 2, 3, 4, 5};
        int[] expected = {1, 2, 3, 4, 5};
        InsertionSort.insertionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test insertionSort on reverse sorted array")
    void testInsertionSortReverseSortedArray() {
        int[] input = {5, 4, 3, 2, 1};
        int[] expected = {1, 2, 3, 4, 5};
        InsertionSort.insertionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test insertionSort on array with duplicate elements")
    void testInsertionSortArrayWithDuplicates() {
        int[] input = {3, 1, 2, 3, 1};
        int[] expected = {1, 1, 2, 3, 3};
        InsertionSort.insertionSort(input);
        Assertions.assertArrayEquals(expected, input);
    }

    @Test
    @DisplayName("Test insertionSort on scrambled array generated by helper method")
    void testInsertionSortScrambledArray() {
        int size = 100;
        int[] data = HelperStaticMethods.generateScrambledIntArray(size);
        int[] expected = HelperStaticMethods.generateSequentialIntArray(size);
        InsertionSort.insertionSort(data);
        Assertions.assertArrayEquals(expected, data);
    }

    @Test
    @DisplayName("Test insertionSort on reverse sequential array generated by helper method")
    void testInsertionSortReverseSequentialArray() {
        int size = 100;
        int[] data = HelperStaticMethods.generateReverseSequentialIntArray(size);
        int[] expected = HelperStaticMethods.generateSequentialIntArray(size);
        InsertionSort.insertionSort(data);
        Assertions.assertArrayEquals(expected, data);
    }

    @Test
    @DisplayName("Test insertionSort throws NullPointerException on null input")
    void testInsertionSortNullArray() {
        Assertions.assertThrows(NullPointerException.class, () -> InsertionSort.insertionSort(null));
    }
}
